### ISSUE TITLE
BMS Driver

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Cerberus#11]
This driver will serve to abstract the outbound BMS CAN commands. We need to collaborate with the BMS team to figure out what commands we need to send over and what messages we need to process. This driver will utilize any CAN driver we develop. This ticket might also encompass writing generic CAN handlers to process BMS data (i.e. given a CAN message, load data into a BMS struct)

**Comment by dyldonahue** [comment]
closing since copied over to `Embedded-Base` [here](https://github.com/Northeastern-Electric-Racing/Embedded-Base/issues/5)
