### ISSUE TITLE
Load Switch Driver

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Cerberus#14]
Part number onboard PDU is LTC4015EUHF#PBF, probably can use naming of ```ltc4015```. This is an I2C driver to drive the IC onboard the PDU, I think that Zach Perry has already done some of this code here iirc: https://github.com/Northeastern-Electric-Racing/LVEmbedded22/blob/LVLoadSwitchDev/STM32CubeIDE/workspace_1.10.1/LVLoadSwitch/Core/Src/main.c

**Comment by nwdepatie** [comment]
Note that the code provided is pretty small, might want to expose more features if possible

**Comment by dyldonahue** [comment]
closing since copied over to `Embedded-Base` [here](https://github.com/Northeastern-Electric-Racing/Embedded-Base/issues/6)
