### ISSUE TITLE
[RTOS] - Steering Wheel Control Logic

### ISSUE THREAD

**Issue by HamzaIqbal69** [Northeastern-Electric-Racing/Cerberus#140]
### Description

Develop control logic for the steering wheel, what buttons will be used for state transitions, moving through menu, etc.

### Acceptance Criteria

Make it work idk

### Proposed Solution

Talk to peyton or nick about how we want to set up steering wheel interface and implement based on that

**Comment by nwdepatie** [comment]
Note that the implementation for denouncing is already in 'steeringio.c' so don't reinvent the wheel (no pun intended), but we need to expand to the different buttons and make them accessible upstream somehow via a queue to a dedicated task maybe.
