### ISSUE TITLE
GPIO Interrupts for buttons

### ISSUE THREAD

**Issue by Sabramz** [Northeastern-Electric-Racing/Cerberus#198]
### Description

Currently we poll buttons every so milliseconds, then de-bounce them. We can use an interrupt for these so we only process a button GPIO input when it matters. In completing this, the button monitor task should be gone.

### Acceptance Criteria

- [ ] Button task is gone
- [ ] Uses interrupt to collect button presses
- [ ] Uses a function that can be easily ported to another interrupt (ex CAN)
- [ ] All data passing uses interrupt context thread safe RTOS utilities

### Proposed Solution

Setup GPIO interrupts in cubeMX, write function to pass button data from interrupt to button debouncing function/task, delete button monitor. Use care when writing code in interrupt, as some RTOS functions are not thread safe when used in an interupt context. To be clear, the context of an interrupt is different from that of a task. [RTFM](https://freertos.org/Documentation/02-Kernel/07-Books-and-manual/01-RTOS_book) if confused ([CMSIS-RTOS docs](https://www.keil.com/pack/doc/CMSIS_Dev/RTOS2/html/group__CMSIS__RTOS.html))

**Comment by jr1221** [comment]
Would this be obsolete for 24A?
