### ISSUE TITLE
Renode Can App

### ISSUE THREAD

**Issue by dyldonahue** [Northeastern-Electric-Racing/Cerberus#207]
### Description

@evanlombardo needs 2 simple apps to talk to each other over CAN to test soem Renode stuff. Lets strip down Cerberus functionality to just listen and broadcast CAN. 

### Acceptance Criteria

Submission of this will be a bit weird because we wont actually merge this in. Submit a PR so we can see if it works, and with that PR, we will tak the compiled .elf files and send them to @evanlombardo once we verify it works

### Proposed Solution

literally just strip Cerberus to just can and simplify the CAN interface

**Comment by jr1221** [comment]
Closed as on branch `test/RenodeCanApp`
