### ISSUE TITLE
[Sense] - Create Accurate LV SoC Calcs

### ISSUE THREAD

**Issue by jr1221** [Northeastern-Electric-Racing/Cerberus#219]
### Description

Create and send LV SoC calcs along with the voltage itself, in the same CAN message.

### Acceptance Criteria

SoC calcs are accurate to the discharge curve and relatively linear.

### Proposed Solution

Use the datasheet for the 24A LV battery, edit the CAN message spec in JSON.

**Comment by harrison-e** [comment]
- Add SoC NetField to `read_lv_sense` CANMsg (`id 0x503`)
- Use [manufacturer Voltage to SoC function](https://www.aegisbattery.com/products/24v-20ah-li-ion-battery-pvc) to calculate SoC from `v_dec`
- Can be integer or decimal percentage 
- Sigmoid?

**Comment by harrison-e** [comment]
- Normal charged voltage = 29.4V
- 18650 max charged voltage = 4.2V
- 29.4V/4.2V = 7 18650's
- Divide overall voltage by 7 to get avg voltage over all rows
- Model with sigmoid function to convert to SoC percentage

**Comment by harrison-e** [comment]
Preliminary changes in `feature/soc` branch (equivalent changes in `Embedded-Base` on `feature/cerb_soc`)
