### ISSUE TITLE
Improving git functionality in docker container

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Cerberus#31]
Currently git is kinda broken in the docker container, as it doesn't use the credentials that are on the host machine. We need to implement a solution that will carry over git credentials and ssh keys from the host machine into the docker container, that way developers can remain in the docker container for the entirety of development rather than having to exit to commit changes

**Comment by dyldonahue** [comment]
closing and moving to Embedded base
