### ISSUE TITLE
Internal State Machine (Planning)

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Cerberus#55]
This is the beginning of a more complex architecture change, where we should have an internal state machine to make sure that we have a robust sense of what state the car is in. last year, we had some different mode (reverse, speed limiting, performance, efficiency) and I'm not sure if we want to add any more modes in. Since we have a lot of modes and might add more in, we need to make sure that the way we make the state machine is extensible and forces developers to account for edge cases during development.

This ticket pertains to the general architecture of how we are going to do this. Should we change the function pointers that tasks are pointing to? Should it just be a bigass switch statement in each task that this is relevant to?

**Comment by nwdepatie** [comment]
![CerberusState drawio](https://github.com/Northeastern-Electric-Racing/Cerberus/assets/80368116/6d5cde11-7547-4c3d-8497-72bc3604932d)
Preliminary State diagram of car to go off of

**Comment by HamzaIqbal69** [comment]
I think function pointers would probably be a cleaner way to do it

**Comment by nwdepatie** [comment]
![image](https://github.com/Northeastern-Electric-Racing/Cerberus/assets/80368116/83ca6c0f-c35b-439d-b297-f1f920842773)
![image](https://github.com/Northeastern-Electric-Racing/Cerberus/assets/80368116/d5aa6bb1-fda6-4ef6-9049-925496d0a04f)
![image](https://github.com/Northeastern-Electric-Racing/Cerberus/assets/80368116/394e491b-15cc-4d0d-a24b-9e341c12d280)

Reference Shepherd SM for more info
https://github.com/Northeastern-Electric-Racing/shepherd_bms/blob/main/shepherd_bms/include/stateMachine.h

**Comment by nwdepatie** [comment]
![image](https://github.com/Northeastern-Electric-Racing/Cerberus/assets/80368116/7f4325f1-c92b-464c-8d89-6bd54be782d0)
![image](https://github.com/Northeastern-Electric-Racing/Cerberus/assets/80368116/40b2f300-9af6-461e-b3e6-bef385308662)

**Comment by nwdepatie** [comment]
This will be a hierarchical state machine, meaning that there will be a Cerberus State, one of which can be Drive. Drive will have multiple sub states. I think that we can probably make Charging a sub state in a similar manner.

**Comment by nwdepatie** [comment]
![image](https://github.com/Northeastern-Electric-Racing/Cerberus/assets/80368116/9f03c596-caed-47cb-8b30-ab73325040ae)

**Comment by nwdepatie** [comment]
Note that we are charging the accumulator out of the car so we need to make sure that we don't attempt to turn the car on if the acucmulator is out, and if the accumulator is detected as being pulled out we need to turn off car as a fault

**Comment by nwdepatie** [comment]
More reference, here is the MPU's state diagram from last year
![mpu_state_diagram drawio](https://github.com/Northeastern-Electric-Racing/Cerberus/assets/80368116/6e9cd3d8-4b8d-4b27-af04-4e7b20980a9a)
